development:
  adapter: postgresql
  database: database_development
  encoding: SQL_ASCII
  pool: 5
  timeout: 5000
  host: localhost
  username: ubuntu
  password: password
test:
  adapter: postgresql
  database: database_test
  encoding: SQL_ASCII
  pool: 5
  timeout: 5000
  host: localhost
  username: ubuntu
  password: password

production:
  adapter: postgresql
  database: database_production
  encoding: SQL_ASCII
  pool: 5
  timeout: 5000
  host: localhost
  username: ubuntu
  password: password